#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define N_MAX_POINTLIGHTS 10
#define N_MAX_DIRECTIONALLIGHTS 10
#define N_MAX_SPOTLIGHTS 10

//Do not edit
#define N_LIGHTS_UNIFORMS 4
#define N_MATRIX_UNIFORMS 6
#define N_SCALAR_UNIFORMS 5
#define N_PARALLAX_UNIFORMS 2
#define N_FOG_UNIFORMS 5

#endif